================================================================================
JobID = 15316406
User = vogg, Account = all
Partition = gpu, Nodelist = agq013
================================================================================
/home/uni08/vogg/monkey-tracking-in-the-wild/src/lib
training chunk_sizes: [2, 2, 2, 2]
The output will be saved to  /home/uni08/vogg/monkey-tracking-in-the-wild/src/lib/../../exp/mot/macaquecp_dla_seed1
Setting up data...
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    main(opt)
  File "train.py", line 39, in main
    dataset = JointDataset(opt, dataset_root, trainset_paths, (1088, 608), augment=True, transforms=transforms)
  File "/home/uni08/vogg/monkey-tracking-in-the-wild/src/lib/datasets/jde.py", line 363, in __init__
    lb = np.loadtxt(lp)
  File "/usr/users/vogg/.conda/envs/mktrack/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1338, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/usr/users/vogg/.conda/envs/mktrack/lib/python3.8/site-packages/numpy/lib/npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/users/vogg/.conda/envs/mktrack/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/users/vogg/.conda/envs/mktrack/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /local/eckerlab/MacaqueCopyPaste/labels_with_ids/01418849d54b3005.txt not found.
